package:
  name: numpy
  version: 1.22.3

build:
  string: py{{ PY_VER }}h{{ PKG_HASH }}_pypi_repack

requirements:
  build:
    - python
  run:
    - python

test:
  commands:
    - python -c "import numpy"

about:
  home: numpy
  license: BSD
  summary: building numpy from pypi
